title: Andreas Textor
email: mail@atextor.de
description: >- # this means to ignore newlines until "baseurl:"
  Andreas Textor's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://atextor.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: atextor
github_username:  atextor

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
